package com.smarttoolfactory.composecolordetector.ui.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFFbb0056)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffd9e1)
val md_theme_light_onPrimaryContainer = Color(0xFF3f0018)
val md_theme_light_secondary = Color(0xFF75565d)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFffd9e0)
val md_theme_light_onSecondaryContainer = Color(0xFF2c151b)
val md_theme_light_tertiary = Color(0xFF7b5733)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffdcbb)
val md_theme_light_onTertiaryContainer = Color(0xFF2d1600)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF201a1b)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF201a1b)
val md_theme_light_surfaceVariant = Color(0xFFf3dee1)
val md_theme_light_onSurfaceVariant = Color(0xFF524346)
val md_theme_light_outline = Color(0xFF847376)
val md_theme_light_inverseOnSurface = Color(0xFFfaeeef)
val md_theme_light_inverseSurface = Color(0xFF352f30)
val md_theme_light_inversePrimary = Color(0xFFffb1c5)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFffb1c5)
val md_theme_dark_onPrimary = Color(0xFF65002b)
val md_theme_dark_primaryContainer = Color(0xFF8f0040)
val md_theme_dark_onPrimaryContainer = Color(0xFFffd9e1)
val md_theme_dark_secondary = Color(0xFFe3bdc4)
val md_theme_dark_onSecondary = Color(0xFF42292f)
val md_theme_dark_secondaryContainer = Color(0xFF5a3f45)
val md_theme_dark_onSecondaryContainer = Color(0xFFffd9e0)
val md_theme_dark_tertiary = Color(0xFFedbd91)
val md_theme_dark_onTertiary = Color(0xFF472a0a)
val md_theme_dark_tertiaryContainer = Color(0xFF60401e)
val md_theme_dark_onTertiaryContainer = Color(0xFFffdcbb)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF201a1b)
val md_theme_dark_onBackground = Color(0xFFece0e1)
val md_theme_dark_surface = Color(0xFF201a1b)
val md_theme_dark_onSurface = Color(0xFFece0e1)
val md_theme_dark_surfaceVariant = Color(0xFF524346)
val md_theme_dark_onSurfaceVariant = Color(0xFFd6c2c5)
val md_theme_dark_outline = Color(0xFF9e8c8f)
val md_theme_dark_inverseOnSurface = Color(0xFF201a1b)
val md_theme_dark_inverseSurface = Color(0xFFece0e1)
val md_theme_dark_inversePrimary = Color(0xFFbb0056)
val md_theme_dark_shadow = Color(0xFF000000)



val seed = Color(0xFFff007b)
val error = Color(0xFFba1b1b)